from . import start
from . import profile
from . import statistics
from . import ratings
from . import referal
from . import mg_search_emoji
from . import mg_identical_in_color
from . import mg_connect_in_order
from . import mg_find_by_list
from . import mg_assemble_a_pair
from . import all_messsage